name: bethany
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  html: ^0.15.5
  dynamic_color: ^1.7.0
  provider: ^6.1.2
  iconly: ^1.0.1
  cached_network_image: ^3.4.1
  hugeicons: ^0.0.7
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  checkmark: ^0.0.2+1
  lucide_icons: ^0.257.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.1
  iconsax: ^0.0.8
  google_fonts: ^6.2.1
  flutter_email_sender: ^6.0.3
  rename_app: ^1.6.1
  build_runner: ^2.4.11
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/logo.png"
  linux:
    generate: true
    image_path: "assets/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  color_dark: "#121212"
  image_dark: assets/logo.png


flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Black.ttf
        - asset: assets/fonts/LexendDeca-Bold.ttf
        - asset: assets/fonts/LexendDeca-ExtraBold.ttf
        - asset: assets/fonts/LexendDeca-ExtraLight.ttf
        - asset: assets/fonts/LexendDeca-Light.ttf
        - asset: assets/fonts/LexendDeca-Medium.ttf
        - asset: assets/fonts/LexendDeca-Regular.ttf
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
        - asset: assets/fonts/LexendDeca-Thin.ttf
